---
- name: "List existing labels"
  uri:
    url: "{{ gitlab_external_url }}/api/{{ gitlab_api_version }}/projects/\
      {{ gitlab_project_id }}/labels"
    method: "GET"
    headers:
      PRIVATE-TOKEN: "{{ gitlab_admin_token }}"
    validate_certs: "{{ gitlab_validate_certs }}"
    return_content: True
  register: labels_list_output

- name: "Get the list of urls in labels"
  set_fact:
    label_name_list: "{{ labels_list_output.json | map(attribute='name') | list }}"

- name: "Add labels"
  uri:
    url: "{{ gitlab_external_url }}/api/{{ gitlab_api_version }}/projects/\
      {{ gitlab_project_id }}/labels"
    method: "POST"
    headers:
      PRIVATE-TOKEN: "{{ gitlab_admin_token }}"
    body:
      name: "{{ item.value.name }}"
      color: "{{ item.value.color }}"
      description: "{{ item.value.description }}"
    body_format: form-urlencoded
    validate_certs: "{{ gitlab_validate_certs }}"
    status_code: 201
  with_dict: "{{ gitlab_labels_list }}"
  when: item.value.name not in label_name_list
